# Generated by Django 5.2.8 on 2025-11-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_property_external_url_property_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='area',
            new_name='area_total',
        ),
        migrations.AlterField(
            model_name='property',
            name='area_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Square meters', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='building_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='is_new_building',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='kitchen_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='living_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='predicted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
